server:
  port: 8888

spring:
  profiles:
    active: local
  flyway:
    locations: ["classpath:db/migration", "classpath:db/sample-data"]
  datasource:
    url: jdbc:h2:~/handson/user;AUTO_SERVER=TRUE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 1000
logging:
  level:
    web: debug