CREATE TABLE
(
  ID                         VARCHAR(50)  NOT NULL,
  USERNAME                   VARCHAR(100) NOT NULL,
  EMAIL                      VARCHAR(100) NOT NULL,
  FIRST_NAME                 VARCHAR(100) NOT NULL,
  LAST_NAME                  VARCHAR(100) NOT NULL,
  PROFILE_IMAGE_URL          VARCHAR(100) NOT NULL,
  STATE                      VARCHAR(100) NOT NULL,
  LATEST_LOGGED_IN_AT        VARCHAR(100) NOT NULL,
  LATEST_PASSWORD_CHANGED_AT BIGINT NULL,
  CREATED_AT                 VARCHAR(100) NOT NULL,
  UPDATED_AT                 VARCHAR(100) NOT NULL
)

CREATE UNIQUE INDEX USERS_USERNAME_INDEX ON USERS(USERNAME);
